package com.sap.xi.basis.alerting.api2;

/**
 * Service implementation of {AlertRetrieveAPI_V2_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "AlertRetrieveAPI_V2_Service", targetNamespace = "http://sap.com/xi/BASIS/alerting/api2", wsdlLocation = "META-INF/wsdl/com/sap/xi/basis/alerting/api2/AlertRetrieveAPI_V2_AlertRetrieveAPI_V2_Service/AlertRetrieveAPI_V2_AlertRetrieveAPI_V2_Service.wsdl")
public class AlertRetrieveAPIV2Service extends javax.xml.ws.Service {

  private final static java.net.URL ALERTRETRIEVEAPIV2SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public AlertRetrieveAPIV2Service() throws java.net.MalformedURLException {
    super(ALERTRETRIEVEAPIV2SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS/alerting/api2", "AlertRetrieveAPI_V2_Service"));
  }
  public AlertRetrieveAPIV2Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [AlertRetrieveAPI_V2_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "AlertRetrieveAPI_V2_Port")
  public com.sap.xi.basis.alerting.api2.AlertRetrieveAPIV2 getAlertRetrieveAPI_V2_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS/alerting/api2","AlertRetrieveAPI_V2_Port");
    return (com.sap.xi.basis.alerting.api2.AlertRetrieveAPIV2) super.getPort(portName,com.sap.xi.basis.alerting.api2.AlertRetrieveAPIV2.class);
  }
  /**
   * Get method for webservice port [AlertRetrieveAPI_V2_PortHTTPS].
   */
  @javax.xml.ws.WebEndpoint(name = "AlertRetrieveAPI_V2_PortHTTPS")
  public com.sap.xi.basis.alerting.api2.AlertRetrieveAPIV2 getAlertRetrieveAPI_V2_PortHTTPS() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS/alerting/api2","AlertRetrieveAPI_V2_PortHTTPS");
    return (com.sap.xi.basis.alerting.api2.AlertRetrieveAPIV2) super.getPort(portName,com.sap.xi.basis.alerting.api2.AlertRetrieveAPIV2.class);
  }
}
