package com.sap.xi.basis.alerting.api2;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "AlertRetrieveAPI_V2", targetNamespace = "http://sap.com/xi/BASIS/alerting/api2")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface AlertRetrieveAPIV2 {

  /**
   * Java representation of web method [RetrieveSingleAlerts].
   */
  @javax.jws.WebMethod(operationName = "RetrieveSingleAlerts", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "RetrieveSingleAlertsResponse_V2", targetNamespace = "http://sap.com/xi/BASIS/alerting/api2", partName = "RetrieveSingleAlertsResponse_V2")
  public com.sap.xi.basis.alerting.api2.RetrieveSingleAlertsOutV2 retrieveSingleAlerts(@javax.jws.WebParam(name = "RetrieveSingleAlertsRequest_V2", targetNamespace = "http://sap.com/xi/BASIS/alerting/api2", partName = "RetrieveSingleAlertsRequest_V2") com.sap.xi.basis.alerting.api2.RetrieveSingleAlertsInV2 retrieveSingleAlertsRequest_V2) throws com.sap.xi.basis.alerting.api2.P2StandardMessageFault;

}
